### ISSUE TITLE
Missing Fully Connected classes

### ISSUE THREAD

**Issue by peguerosdc** [therooler/piqmc#1]
Hi! Thank you very much for sharing!

After checking `python_interface.py`, it seems that `qmc` and `sa` modules should have functions called `QuantumAnnealFullyConnected` and `AnnealFullyConnected`, respectively, but they are missing.

As a result, the fully connected examples fail like in the following case:

````
$ python run_PIQMC_Wishart.py
True groundstate energy per spin:  -0.25126008065
Loading checkpoint!
Failed! Running from scratch
annealing run =  1
Annealing times to be run = [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384]
num_sweeps = 5
gamma_0 =  1.0
P =  100
Temperature so that P * T = 1.0: 0.01

Energy per spin before pre-annealing is: 0.003150201631250002
Traceback (most recent call last):
  File "run_PIQMC_Wishart.py", line 53, in <module>
    Energies[annealingrun-1] = Q.perform_tau_schedule()
  File "/home/peguerosdc/development/piqmc/python_interface.py", line 132, in perform_tau_schedule
    self.pre_anneal()
  File "/home/peguerosdc/development/piqmc/python_interface.py", line 80, in pre_anneal
    sa.AnnealFullyConnected(self.preannealing_sched,
AttributeError: module 'piqmc.sa' has no attribute 'AnnealFullyConnected'
````

Any chance these functions could be added?

EDIT: I think they should be `functions` instead of `classes` as I previously thought

**Comment by mhibatallah** [comment]
Thanks very much for your comment and for your interest in our code! We accidentally forgot to update this part of the code and we are glad you pointed it out. I have now added the fully connected functions, now it should hopefully work.

**Comment by peguerosdc** [comment]
Thank you for the quick reply!

Apparently, it is still not working, but now I can't find the issue. I tried cloning the repo and installing again from scratch (I am using virtual envs to avoid possible conflicts) and I still receive the same `AttributeError` message.

I have no prior experience with Cython, so if this is a "compilation" error of some sort, I definitely will be missing it. Any ideas or additional information I can give to help debug this?

**Comment by therooler** [comment]
I just did a fresh clone of our repo and reproduced the issue. It turns out something weird was happening with the Cython compilation. Sorry about this... Changing 
```
import cython
```
to 
```
cimport cython
```
in both the Cython files did the trick: the error disappeared and the Wishart example ran as expected.  I'm not sure why this happened, maybe we used an old version of Cython before, which is why it only shows up now. I pushed the changes to the Cython code so all should be good now.

Let me know if you got it working.

**Comment by peguerosdc** [comment]
Got it! I confirm it is working now, thank you! I will close the issue.

PS: `python_interface.py` is asking to import `matplotlib`, but it's never used. This causes the examples to fail as that module is not listed in `environment.yml` (it needs to be installed separately), so I think it would be good to either add it to the dependencies or to remove the import 🙂

**Comment by therooler** [comment]
Oh right, fixed that as well. Thanks for taking the time to report all these issues :sweat_smile:
